# Generated by Django 4.2.4 on 2023-08-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('initialPrice', models.FloatField(blank=True, null=True)),
                ('finalPrice', models.FloatField(blank=True, null=True)),
                ('initialDate', models.DateTimeField(blank=True, null=True)),
                ('finalDate', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('descrpition', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=20, null=True)),
                ('lastName', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('bank', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=15, null=True)),
                ('agency', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
