# Generated by Django 4.2.4 on 2023-08-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.IntegerField(blank=True, null=True)),
                ('id_place', models.IntegerField(blank=True, null=True)),
                ('initialDate', models.DateTimeField(blank=True, null=True)),
                ('payday', models.DateTimeField(blank=True, null=True)),
                ('finalDate', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('payment', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='finalDate',
        ),
        migrations.RemoveField(
            model_name='place',
            name='finalPrice',
        ),
        migrations.RemoveField(
            model_name='place',
            name='initialDate',
        ),
        migrations.RemoveField(
            model_name='place',
            name='initialPrice',
        ),
        migrations.AddField(
            model_name='place',
            name='id_owner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
