# Generated by Django 4.2.4 on 2023-08-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaction_id_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaction', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id_transaction',
        ),
    ]
