# Generated by Django 4.2.4 on 2023-08-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chargeback_remove_transaction_id_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargeBack',
        ),
    ]
