# Generated by Django 4.2.3 on 2023-07-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_user_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Data_de_aniversário',
            new_name='Data_de_aniversario',
        ),
    ]
