# Generated by Django 4.2.3 on 2023-08-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idClient', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('idPlace', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='descrpition',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='score',
        ),
    ]
