# Generated by Django 4.2.4 on 2023-08-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id_transaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
