# Generated by Django 4.2.3 on 2023-07-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_agencia_alter_user_banco_alter_user_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Agencia',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Banco',
        ),
        migrations.RemoveField(
            model_name='user',
            name='CPF',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Celular',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Conta',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Data_de_aniversario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Senha',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nome',
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
