# Generated by Django 4.2.3 on 2023-08-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id_advertiser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionState',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
