# Generated by Django 4.2.3 on 2023-08-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_place_termsofuse'),
        ('api', '0005_score_rename_descrpition_place_description_and_more'),
        ('api', '0005_transaction_id_advertiser_and_more'),
    ]

    operations = [
    ]
