# Generated by Django 4.2.4 on 2023-08-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20230817_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='checked',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
