# Generated by Django 4.2.3 on 2023-07-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('initialPrice', models.FloatField(blank=True, max_length=20, null=True)),
                ('finalPrice', models.FloatField(blank=True, max_length=20, null=True)),
                ('initialDate', models.DateTimeField(blank=True, null=True)),
                ('finalDate', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='bank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
