# Generated by Django 4.2.4 on 2023-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_place_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='termsofuse',
            new_name='terms_of_use',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='idClient',
            new_name='id_client',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='idPlace',
            new_name='id_place',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='finalDate',
            new_name='final_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='initialDate',
            new_name='initial_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionDate',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionState',
            new_name='transaction_state',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='place',
            name='checked',
            field=models.IntegerField(choices=[(-1, 'Rejected'), (0, 'Pending'), (1, 'Accepted')], default=0),
        ),
    ]
