# Generated by Django 4.2.3 on 2023-07-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_place_alter_user_bank_alter_user_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='finalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='initialPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
