# Generated by Django 4.2.3 on 2023-08-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_termsofuse_place_terms_of_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='place_images/image_1/'),
        ),
        migrations.AddField(
            model_name='place',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='place_images/image_2/'),
        ),
        migrations.AddField(
            model_name='place',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='place_images/image_3/'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
