# Generated by Django 4.2.3 on 2023-07-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_place_finalprice_alter_place_initialprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='filter',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
