# Generated by Django 4.2.3 on 2023-08-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_transaction_location_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
