# Generated by Django 4.2.3 on 2023-07-14 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_place_descrpition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='finalPrice',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='place',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='place',
            name='finalDate',
        ),
        migrations.RemoveField(
            model_name='place',
            name='initialDate',
        ),
        migrations.RemoveField(
            model_name='place',
            name='initialPrice',
        ),
    ]
