# Generated by Django 4.2.3 on 2023-07-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_finalprice_place_price_remove_place_filter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='descrpition',
            new_name='description',
        ),
    ]
