# Generated by Django 4.2.3 on 2023-08-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image_3',
        ),
    ]
