# Generated by Django 4.2.3 on 2023-07-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_descrpition_place_descripition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Price',
            new_name='price',
        ),
    ]
