# Generated by Django 4.2.3 on 2023-07-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_place_price'),
        ('api', '0014_rename_price_place_price'),
    ]

    operations = [
    ]
